@host = http://localhost:5047
@baseUrl = {{host}}/api/students

### 1. Получить весь список студентов
GET {{baseUrl}}

### 2. Поиск студентов по подстроке (Query-параметр)
GET {{baseUrl}}?search=Мария

### 3. Получить конкретного студента по числовому ID (Route-параметр)
GET {{baseUrl}}/2

### 4. Попытка получить студента с несуществующим ID (Ожидается 404)
GET {{baseUrl}}/999

### 5. Добавить нового студента (Тело запроса в JSON)
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Николай Николаев",
  "group": "ИП-24"
}

### 6. Полное обновление данных студента (PUT)
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name": "Иван Обновленный",
  "group": "ИП-25"
}

### 7. Частичное изменение группы студента (PATCH)
PATCH {{baseUrl}}/2/group
Content-Type: application/json

"ИП-99"

### 8. Удаление студента по ID (DELETE)
DELETE {{baseUrl}}/1

### 9. Проверка удаления: попытка повторно удалить того же студента (Ожидается 404)
DELETE {{baseUrl}}/1