@host = http://localhost:5287

### ==========================================
### ПРОВЕРКА НА ОЦЕНКУ «3»
### ==========================================

### 3.1 Получить все книги
GET {{host}}/api/books
Accept: application/json

### 3.2 Получить книгу по существующему ID
GET {{host}}/api/books/2
Accept: application/json

### 3.3 Получить книгу по несуществующему ID (Ожидается 404 Not Found)
GET {{host}}/api/books/999
Accept: application/json


### ==========================================
### ПРОВЕРКА НА ОЦЕНКУ «4»
### ==========================================

### 4.1 Добавить новую книгу (ID должен сгенерироваться автоматически)
POST {{host}}/api/books
Content-Type: application/json

{
  "title": "Война и мир",
  "author": "Толстой Л.Н.",
  "year": 1869
}

### 4.2 Удалить книгу по ID
DELETE {{host}}/api/books/1

### 4.3 Удалить несуществующую книгу (Ожидается 404 Not Found)
DELETE {{host}}/api/books/999


### ==========================================
### ПРОВЕРКА НА ОЦЕНКУ «5»
### ==========================================

### 5.1 Проверка ограничения маршрута: Ошибка валидации строки (Ожидается 404 или 400 на уровне роутинга)
GET {{host}}/api/books/abc

### 5.2 Фильтрация по автору (Регистр не должен иметь значения. Ожидается список книг Гоголя)
GET {{host}}/api/books?author=гоголь
Accept: application/json

### 5.3 Частичное обновление названия (PATCH)
PATCH {{host}}/api/books/2/title
Content-Type: text/plain

Новое название книги Х

